### ISSUE TITLE
Remove the OpenCodeGraph VSCode extension from marketplace

### ISSUE THREAD

**Issue by tinvaan** [sourcegraph/openctx#80]
Now that OCG is rebranded as OpenCtx, should we take down the old [VSCode extension](https://marketplace.visualstudio.com/items?itemName=sourcegraph.opencodegraph)? The new OpenCtx VScode extension is live [here](https://marketplace.visualstudio.com/items?itemName=sourcegraph.openctx).

**Comment by sqs** [comment]
Thank you. Done.
